### PR TITLE
Updated some files for tensorflow 0.12 with deprecated functions

### PR DESCRIPTION
**Pull request by leonardomn**
Updated some files for tensorflow 0.12 with deprecated functions.

### CODE REVIEW

**Comment by 4pal** [comment]
I trained some data using train.py for some days for chatbot rnn.Whenever i submit text i get this error:   
    _, states[0] = net.forward_model(sess, states[0], vocab[char])
KeyError: u'>'

**Comment by pender** [comment]
@4pal, you must have trained on a corpus that did not contain the '>' character. Per the readme, training data should be one or more newline-delimited text files. Each line of dialogue should begin with "> " and end with a newline.

This repo is very much behind the times -- IIRC, it was built for the Tensorflow v0.11 API, and there are [better architectures](https://arxiv.org/abs/1706.03762) for natural language sequence prediction now anyway.

**Comment by 4pal** [comment]
hi pender, i actually used your chatbot.you mean i cannot use it now.the error i mentioned above comes when i uploaded the .pkl ,.ckpt and checkpoint file on model/reddit. I cannot chat with the bot as  get the KeyError issue.

**Comment by pender** [comment]
Hi, I pushed a significant update to TF 1.4 and Python3, so I am closing out old PRs. The new version should work with the pretrained model that is available for download (linked in the readme). Thanks!

**Pull request closed without merging**
